"""Untrained-model baseline on each frozen evaluation split.

Reads the ``evaluation-*.jsonl`` files written by ``scripts/audit_datasets.py``
(or any experiment run), samples up to ``--per-split`` rows per split with a
fixed seed, and scores the base model's greedy answers with the same exact
parsers the experiments use. Generation goes through
``HuggingFaceCausalLMAdapter`` so the prompt format matches training.

    python scripts/baseline_eval.py --data /tmp/onwordly-audit --report docs/baseline.md
"""
from __future__ import annotations

import argparse
import json
import random
import time
from pathlib import Path

from onwordly.models.huggingface import HuggingFaceCausalLMAdapter
from onwordly.training.evaluation import lenient_match
from onwordly.verifiers.arithmetic import parse_integer_answer
from onwordly.verifiers.formal_logic import parse_logic_answer
from onwordly.verifiers.symbolic import parse_symbolic_answer

DOMAINS = {
    "001": ("arithmetic", lambda response, answer: parse_integer_answer(response) == answer),
    "003": ("symbolic", lambda response, answer: parse_symbolic_answer(response) == answer),
    "004": ("string", lambda response, answer: response.strip() == answer),
    "005": ("program", lambda response, answer: parse_integer_answer(response) == answer),
    "006": ("logic", lambda response, answer: parse_logic_answer(response) == answer),
}


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", required=True)
    parser.add_argument("--model", default="Qwen/Qwen2.5-0.5B")
    parser.add_argument("--per-split", type=int, default=100)
    parser.add_argument("--max-new-tokens", type=int, default=32)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--device", default="auto", help="auto, cpu, cuda or mps")
    parser.add_argument("--report")
    parser.add_argument(
        "--chat-template",
        action="store_true",
        help="wrap each prompt in the tokenizer's chat template (instruct models)",
    )
    args = parser.parse_args(argv)

    adapter = HuggingFaceCausalLMAdapter(
        args.model, max_new_tokens=args.max_new_tokens, device=args.device, seed=args.seed
    )
    def render(prompt: str) -> str:
        if not args.chat_template:
            return prompt
        return adapter.tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False,
            add_generation_prompt=True,
        )

    rng = random.Random(args.seed)
    results: dict[str, dict[str, dict[str, object]]] = {}
    for experiment, (domain, check) in DOMAINS.items():
        for path in sorted(Path(args.data, experiment).glob("evaluation-*.jsonl")):
            rows = [json.loads(line) for line in path.read_text().splitlines() if line]
            sample = rng.sample(rows, min(args.per_split, len(rows)))
            started = time.perf_counter()
            correct, lenient, parsed, examples = 0, 0, 0, []
            for row in sample:
                response = adapter.generate(render(row["prompt"]))
                ok = bool(check(response, row["answer"]))
                correct += ok
                lenient += lenient_match(response, row["answer"])
                if len(examples) < 3:
                    examples.append({"answer": row["answer"], "response": response[:80]})
                parsed += response.strip() != ""
            split = path.stem.removeprefix("evaluation-")
            results.setdefault(f"{experiment} {domain}", {})[split] = {
                "n": len(sample),
                "accuracy": round(correct / len(sample), 3),
                "lenient_accuracy": round(lenient / len(sample), 3),
                "nonempty": round(parsed / len(sample), 3),
                "seconds": round(time.perf_counter() - started, 1),
                "examples": examples,
            }
            print(experiment, split, results[f"{experiment} {domain}"][split]["accuracy"], flush=True)

    Path(args.data, "baseline.json").write_text(json.dumps(results, indent=2))
    if args.report:
        lines = [
            "# Untrained baseline",
            "",
            f"`{args.model}`{' with its chat template' if args.chat_template else ', raw prompts'}, greedy, {adapter.device_name},",
            f"{args.per_split} sampled rows per split (seed {args.seed}),",
            "scored with the experiments' exact parsers. Generated by `scripts/baseline_eval.py`.",
            "Sample sizes are small; treat differences under ~10 points as noise.",
            "",
            "Lenient = expected answer appears anywhere in the response (diagnostic upper",
            "bound on capability ignoring format; restated prompts can inflate it).",
            "",
            "| Domain | Split | n | Exact | Lenient | Sample response (expected) |",
            "| --- | --- | ---: | ---: | ---: | --- |",
        ]
        for domain, splits in results.items():
            for split, row in splits.items():
                example = row["examples"][0]
                response = example["response"].replace("|", "\\|").replace("\n", " ")
                lines.append(
                    f"| {domain} | {split} | {row['n']} | {row['accuracy']:.2f} | {row['lenient_accuracy']:.2f} | "
                    f"`{response}` (`{example['answer']}`) |"
                )
        Path(args.report).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
